name: PR test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}


jobs:
  build:
    name: pr-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Verify Terraform installation
        run: terraform version

      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
        with:
          version: 'latest'

      - name: Install gpgme # dep of github.com/containers/image/v5/signature
        run: sudo apt-get install -y libgpgme-dev

      - name: Run GoReleaser check
        uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6.0.0
        with:
          args: check --verbose

      - name: Build
        run: make
